[package]
name = "glance-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "string"] }
directories = "6"
glance-lib = { path = "../glance-lib" }
glance-util = { path = "../glance-util" }
serde_json = "1"
sloggers = "2"
slog = "2"
