
name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Gtk
      run: sudo apt update && sudo apt-get install libgtk-3-dev
    - name: Install Dioxus
      run: sudo apt update && sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
